### ISSUE TITLE
model files

### ISSUE THREAD

**Issue by JLiLab** [BIOP/ijl-utilities-wrappers#25]
where can I download the pre-trained models for Stardist? Thanks,

**Comment by romainGuiet** [comment]
Hi @JLiLab ,
you can find all data on the [zenodo repo]( https://zenodo.org/record/6645978#.ZB1L8nbMIQ8)
I will add a link to it in the documentation,
Cheers,
Romain

**Comment by JLiLab** [comment]
Thank you for the quick reply!

After I downloaded the models and tried the plugin, I got the following error:

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at ch.epfl.biop.wrappers.stardist.ij2commands.StarDist2D_SegmentImgPlus_Advanced.run(StarDist2D_SegmentImgPlus_Advanced.java:118)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more

I got the same error message when I tried to do Stardist2D. 

To make sure if my Conda environment is OK, I tested Stardist2D and it ran perfectly. But when I do 3D (i.e. stardist-predict3d -i Whole_ds441a.tif -m C:\Users\zeiss\Documents\Fiji.app\models\n1_stardist_96 -o D:\Downloads), I got the following error: 
2023-03-24 17:25:04.303900: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6281 MB memory) -> physical GPU (device: 0, name: Quadro RTX 4000, pci bus id: 0000:2d:00.0, compute capability: 7.5)
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.587371, nms_thresh=0.3.
Traceback (most recent call last):
  File "C:\Users\zeiss\.conda\envs\stardist\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\zeiss\.conda\envs\stardist\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zeiss\.conda\envs\stardist\Scripts\stardist-predict3d.exe\__main__.py", line 7, in <module>
  File "C:\Users\zeiss\.conda\envs\stardist\lib\site-packages\stardist\scripts\predict3d.py", line 85, in main
    nms_thresh=args.nms_thresh)
  File "C:\Users\zeiss\.conda\envs\stardist\lib\site-packages\stardist\models\base.py", line 775, in predict_instances
    for r in self._predict_instances_generator(*args, **kwargs):
  File "C:\Users\zeiss\.conda\envs\stardist\lib\site-packages\stardist\models\base.py", line 728, in _predict_instances_generator
    prob_thresh=prob_thresh, show_tile_progress=show_tile_progress, **predict_kwargs):
  File "C:\Users\zeiss\.conda\envs\stardist\lib\site-packages\stardist\models\base.py", line 538, in _predict_sparse_generator
    self._predict_setup(img, axes, normalizer, n_tiles, show_tile_progress, predict_kwargs)
  File "C:\Users\zeiss\.conda\envs\stardist\lib\site-packages\stardist\models\base.py", line 381, in _predict_setup
    self.config.n_channel_in == x.shape[channel] or _raise(ValueError())
  File "C:\Users\zeiss\.conda\envs\stardist\lib\site-packages\csbdeep\utils\utils.py", line 91, in _raise
    raise e
ValueError

I will appreciate your help!

**Comment by JLiLab** [comment]
It might be an issue with a mismatch issue between CUDA and cuDNN. After I changed it following the instruction, the 2D works now.

**Comment by romainGuiet** [comment]
Hi @JLiLab ,

so it's all good ?

**Comment by JLiLab** [comment]
All good!
