### ISSUE TITLE
Error with Adding BIOP to FIJI due to JAVA 

### ISSUE THREAD

**Issue by Gaborandi** [BIOP/ijl-utilities-wrappers#35]
Every time i try to use it through FIJI, i get this error : 

java.io.IOException: Cannot run program "elastix": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at ch.epfl.biop.wrappers.elastix.Elastix.execute(Elastix.java:93)
	at ch.epfl.biop.wrappers.elastix.DefaultElastixTask.run(DefaultElastixTask.java:33)
	at ch.epfl.biop.wrappers.elastix.RegisterHelper.align(RegisterHelper.java:195)
	at ch.epfl.biop.wrappers.elastix.ij2commands.Elastix_Register.run(Elastix_Register.java:99)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:453)
	at java.lang.ProcessImpl.start(ProcessImpl.java:139)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 13 more

i would appreciate any help to solve this issue !!

**Comment by lacan** [comment]
Hi, 

The error is quite explicit. It cannot find the elastix executable. 
In the Elastix instructions
https://github.com/BIOP/ijl-utilities-wrappers#elastix-and-transformix

> To use the wrapper, first install the [binaries of elastix](https://github.com/SuperElastix/elastix/releases/tag/5.0.1) (transformix is included) for your OS. Then, in Fiji, you can start the Set and Check Wrappers command:
