### ISSUE TITLE
Stardist 3D Wrapper crashing at launch

### ISSUE THREAD

**Issue by gabriel5222** [BIOP/ijl-utilities-wrappers#42]
Hello,

I'm currently running into an issue with the Stardist 3D Wrapper.

I follow the instruction for the installation and everything went smoothly, but when I tried to launch the plugin with the Stardist 3D advanced option it just crashes and I got this error message from the console:

[ERROR] Command errored: StarDist3D... (Advanced)
java.lang.NullPointerException
	at ch.epfl.biop.wrappers.stardist.ij2commands.StarDist3D_SegmentImgPlus_Advanced.run(StarDist3D_SegmentImgPlus_Advanced.java:119)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Do you have an idea of how to fix this issue ? I already tried to reinstall everything with a new FIJI.

Thanks in advanced and have a nice day

**Comment by NicoKiaru** [comment]
Do you have any error message other than this one ? Do you have a minimal way to reproduce the issue ?

ping @romainGuiet

**Comment by gabriel5222** [comment]
I also have another window named exception with this error message: 

(Fiji Is Just) ImageJ 2.14.0/1.54j; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 732MB of 97918MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:128)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at ch.epfl.biop.wrappers.stardist.ij2commands.StarDist3D_SegmentImgPlus_Advanced.run(StarDist3D_SegmentImgPlus_Advanced.java:119)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	... 6 more

And yes I can easily  reproduce this issue, I just have to launch the analyse

**Comment by romainGuiet** [comment]
Hi @gabriel5222 ,

>And yes I can easily reproduce this issue, I just have to launch the analyse

I think that what Nico meant was more details about how you use the plugin. Which dataset, which model ...

In order to help you found the issue, could you download from this [zenodo repository](https://zenodo.org/records/6645978) the : 
- [models.zip](https://zenodo.org/records/6645978/files/models.zip?download=1)
- [annotations_BIOP.zip](https://zenodo.org/records/6645978/files/annotations_BIOP.zip?download=1)

Unzip them all and try to use the plugin again, using one of the models and one of the image

and if it crashes again : 
- from the command in the Fiji console :
```
[cmd.exe /C CALL conda.bat activate D:\conda\conda-envs\stardist-085-gpu & stardist-predict3d -i C:\Users\guiet\AppData\Local\Temp\StarDistTemp\_CCK_6_ACQ_8#1_001_1_2-t1.tif -m C:\Fiji.app\models\stardist3D\dataset_mergev1_n1_stardist_96_(1.3 1 1)_(48 64 64)_(1 1 1) -o C:\Users\guiet\AppData\Local\Temp\StarDistTemp]
```
- start your stardist environment 
- use the command : 
``` stardist-predict3d -i $PATH_TO_INPUT -m $PATH_TO_MODEL -o $PATH_TO_OUTPUT ```

Cheers,

R

**Comment by gabriel5222** [comment]
Hello,

Thanks for your advices. I've tried to launch Stardist on Fiji using some of the images and some of the models from the zenodo repository but I keep having the same issue (also the model I was using previously was the late_blastocyst_model.

The command stardist-predict3d worked and now I can use Stardist 3D directly from my stardist environment.

Thanks again
